### ISSUE TITLE
restest-cli.jar not in directory

### ISSUE THREAD

**Issue by henning410** [isa-group/RESTest#267]
I followed "Option 1: Build RESTest from source". The build worked and I have some `restest.jar`. 
Unfortunately I cannot find anny restest-cli.jar file.

**Comment by josgarmar31** [comment]
After executing the command specified in option one, the file restest.jar is placed within the target folder, which can be found at the root of the project.

**Comment by henning410** [comment]
I am not searching for `restest.jar` file. Instead I try to use the following from your Readme: 
_Generate, Execute, and Generate Reports based on OpenAPI specification:_
`java -jar restest-cli.jar -o [path_to_oas_file] `

For this, I need some `restest-cli.jar` which I can't find.

**Comment by josgarmar31** [comment]
My apologies, this is due to an error we made in creating the Readme content. The correct command to execute is java -jar .\target\restest-cli.jar -o [path_to_oas_file], as I mentioned in the previous message, the jar files are located within the target folder. I appreciate you catching this error, and we're available if you have any further questions.
