### ISSUE TITLE
i downloaded the latest version of the zip file, why is there no restest.jar inside?

### ISSUE THREAD

**Issue by BigMasterGithub** [isa-group/RESTest#269]
![image](https://github.com/isa-group/RESTest/assets/68625512/0df8b0b3-0331-4e86-a29f-09f03a2cb309)

**Comment by henning410** [comment]
I have the same problem, look at my issue and especially at my last comment: 
https://github.com/isa-group/RESTest/issues/267

But they unfortunately closed this issue even if it was not solved yet :/

**Comment by henning410** [comment]
@BigMasterGithub did you get it working? I am still hoping for a response from the authors

**Comment by BigMasterGithub** [comment]
> @BigMasterGithub did you get it working? I am still hoping for a response from the authors

no ， i give up it~

**Comment by josgarmar31** [comment]
My apologies for the delay. Regarding how to obtain 'restest.jar,' you can get it by downloading the latest release of the framework and executing 'mvn clean install -DskipTests.' On the other hand, in order to use 'restest-cli.jar,' it is necessary to download the latest version from the master branch, as we are still working on improvements to the command-line interface, and there is no information available about it in the latest release."

**Comment by BigMasterGithub** [comment]
@josgarmar31  Thanks again for developing the tool！

**Comment by henning410** [comment]
Thanks for your answer, `restest-cli.jar` is now there :)
